### ISSUE TITLE
Finnish player names are not in different color

### ISSUE THREAD

**Issue by Hamatti** [Hamatti/nhl-235#4]
<img width="421" alt="Screenshot of Anaheim Colorado game with Donskoi and Rantanen as scorers" src="https://user-images.githubusercontent.com/1909996/105573629-96537a80-5d67-11eb-81b0-039ccde9d13f.png">

One of the unique touches of the original YLE Tekstitv 235 is that it displays Finnish players in green color. This is obviously only helpful for Finnish audience but it's a twist I'd like to keep. No idea how to solve right now since there's no info of the player's country in the data.

Recording this issue so I don't forget it one day.

Sidenote: Consider adding a flag to bypass it for non-Finnish users

**Comment by oylenshpeegul** [comment]
The API does seem to have that data for each player

```
$ GET https://statsapi.web.nhl.com/api/v1/people/8475820 | jq '.people[]["fullName", "nationality"]'
"Joonas Donskoi"
"FIN"

$ GET https://statsapi.web.nhl.com/api/v1/people/8478420 | jq '.people[]["fullName", "nationality"]'
"Mikko Rantanen"
"FIN"

$ GET https://statsapi.web.nhl.com/api/v1/people/8476455 | jq '.people[]["fullName", "nationality"]'
"Gabriel Landeskog"
"SWE"
```

I don't know the best strategy for tracking that. In addition to nationality, there is also birthCountry

```
$ GET https://statsapi.web.nhl.com/api/v1/people/8475820 | jq '.people[]["fullName", "nationality", "birthCountry"]'
"Joonas Donskoi"
"FIN"
"FIN"
```

I don't know what you'd want to do if those differed.

**Comment by Hamatti** [comment]
@oylenshpeegul Thanks for the tip, this is super helpful.

I'll have to take a look at NHL's StatsAPI (since I'm currently using a different one) and see if I can either switch into that for all or to see if I can figure out a mapping between names and their IDs to get the nationalities there.

**Comment by oylenshpeegul** [comment]
Heh. So I just followed the link in your README to the nhl-score-api. I guess I didn't read carefully enough to get that the statsapi was different. But at least they're related. So the team and player names are written the same.

If we fetched all the teams, then fetched the roster for each team, then fetched the nationality for each player for each roster, that would do it. That's a lot of API fetching though. We wouldn't want to do it each time we run 235. I suppose if we wrote the results to a file, we could read the data from there until there's a trade or some other roster change.

One advantage to doing this is we could grab a proper lastName for each player and save that too. That might work better than the current method. I wrote [a Perl script to do this](https://gist.github.com/oylenshpeegul/7d15207d7ec2b7462766076697e450a8). It creates [people.json](https://gist.github.com/oylenshpeegul/73c2f663a47f09e55127aee58ee95bb0). Here is what it looks like pretty-printed

```json
{
  "ANA": {
    "Adam Henrique": {
      "lastName": "Henrique",
      "nationality": "CAN"
    },
    "Ben Hutton": {
      "lastName": "Hutton",
      "nationality": "CAN"
    },
    "Cam Fowler": {
      "lastName": "Fowler",
      "nationality": "USA"
    },
 ...
    "Trevor van Riemsdyk": {
      "lastName": "van Riemsdyk",
      "nationality": "USA"
    },
    "Vitek Vanecek": {
      "lastName": "Vanecek",
      "nationality": "CZE"
    },
    "Zdeno Chara": {
      "lastName": "Chara",
      "nationality": "SVK"
    }
  }
}
```

Now 235 could read from this local file and change its behavior accordingly. I don't think it would be hard to rewrite this in Rust. You could even consider making 235 have subcommands for updating it or whatever. Of course, now 235 has local data, which I guess means configuration (where is this file?).

**Comment by Hamatti** [comment]
> That's a lot of API fetching though.

Yeah, that is currently one of the reasons why I'm probably gonna not add this feature in unless either the current API I use adds player data or I end up switching to another that makes it straight-forward.

Last night alone, there were over 80 goals scored so to avoid slowing it down, there would have to be a way that doesn't require extra calls.

> we could read the data from there until there's a trade or some other roster change.

This is also something I considered in the beginning but I'm afraid it would have too many false results since trades, signups and calling players up from taxi squad or AHL can happen between any games.

**Comment by oylenshpeegul** [comment]
It occurred to me that since we're keying the players on their names only, we can ditch the teams. Then we don't care about trades, as long as the name is on *some* roster.  [I made a version that does this](https://github.com/oylenshpeegul/nhl-scores). I can't yet say how robust it is.

We could even keep accumulating names from prospect lists, minor leagues, and so on. Perhaps we'd never have to remove a name. I don't know what to do if there's a duplicate name though. The score api doesn't seem to use the ids from the stats api.

**Comment by Hamatti** [comment]
Closing this due to #37
