### ISSUE TITLE
Windows line ending in configuration file

### ISSUE THREAD

**Issue by frogshead** [Hamatti/nhl-235#48]
Hi @Hamatti  this was the actual beef why needed to build by myself 😄 

Windows causes troubles if multiple lines in configuration file. As the '\r' is left to string after splitting '\n'

I think this will fix it
```rust
    let highlights: Vec<String> = contents
        .split('\n')
        .map(|s| s.trim_end().to_string())
        .filter(|s| s != "")
        .collect();
```
However still learning rust so not sure if there is more elegant solution and still struggling how i could add a unit test for the case.

**Comment by Hamatti** [comment]
Let's learn together!

I googled a bit and found this suggestion for clippy: https://github.com/rust-lang/rust-clippy/issues/8733

> Suggest replacing string.split("\n"), string.split('\n'), and string.split("\r\n") with string.lines().

This means in `main.rs:130`, you could replace `.split('\n')` with `.lines()`.

Could you give that a go, see if it works on Windows and if it does, make a pull request?

**Comment by Hamatti** [comment]
For unit test, I'm not against splitting that part into a unit test that takes in `contents` and parses that into `highlights`.

That would make it easier to test as it doesn't rely on reading from filesystem.

**Comment by frogshead** [comment]
It seems to work and created pr just for the fix.

Should I create own ticket for unit test? Splitting the function could be good idea also if there is some use case to give configuration file as a command line argument. For me, the current implementation is 💯 to show stats of Finnish players and mimic the teksti-tv without opening tv.

**Comment by Hamatti** [comment]
> Should I create own ticket for unit test?

You could add the unit test into the same PR, that way the implementation and its test come in at the same time.

**Comment by frogshead** [comment]
sure, will do it later 👍

**Comment by Hamatti** [comment]
👍 

If you run into any issues that you'd need help with, don't hesitate to ask!
